server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # API routing is handled by the AWS Application Load Balancer
    # so we don't need to proxy_pass here anymore.
}